title: Supra Coders
logo: "/assets/images/SpaceCoders_Logo.png"


email:
description: >- # this means to ignore newlines until "baseurl:"
  Supra Coders - #BuiltByTheForce
subtitle: "#BuiltByTheForce"
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: airmencoders/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: true
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Space Coders"
  avatar : "/assets/images/SpaceCoders_Logo.png"
  bio    : "Enabling the Space Force's members to code"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SpaceCoders"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/company/airmencoders/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      sidebar:
        nav: "side"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "side"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
